### ISSUE TITLE
change view for longer period of data

### ISSUE THREAD

**Issue by cricou76** [tr-o/GAS-Dynamic-Data-Visualizer#4]
Hello
Thanks again for the code you developp between switchbot data on google sheet and the visualization on diagram
can i ask you an update or an explaination ?
the charts only shown the latest 24h from data in google sheet, is it possible to extend this, using choice on the index html to have :

- latest 24h
- latest 7 days
- latest 30 days
- latest year
- ALL 

many thanks again !

Cricou

**Comment by tr-o** [comment]
Hello Cricou,

I've incorporated the requested changes and pushed the updates to a new branch on the GitHub repository. The new branch is named `tr-o-patch-4`. 

Here is the link to the branch: [tr-o-patch-4](https://github.com/tr-o/GAS-Dynamic-Data-Visualizer/tree/tr-o-patch-4)

In this branch, I've updated the files `Code.gs` and `index.html`. You can now select different time spans for data visualization from a dropdown menu at the top of the page. The options are: the latest 24 hours, the latest 7 days, the latest 30 days, the latest year, and all data.

To test the new feature, please download the code from the branch `tr-o-patch-4`, replace your current files with these updated versions, and let me know if everything works as expected.

Once you have confirmed that the changes meet your needs, I will merge this branch into the main branch.

Please feel free to reach out if you encounter any issues or if you have further requests.

Best regards,
tr-o

**Comment by cricou76** [comment]
Hello, you're absolutly amazing ! 
Thanks for the update it works perfectly.
All the draw are now available exactly as i needed, many thanks again for the merge

i've lot futures idea to improve the charts view, the html page etc...:)

regards

**Comment by tr-o** [comment]
Hello Cricou,

I'm glad to hear that the update worked perfectly for you! I'm happy to have been able to help you merge the code and meet your needs.

It's great to hear that you have future ideas to improve the charts view and the HTML page. Feel free to explore and implement those ideas. If you need any further assistance or have any questions along the way, don't hesitate to reach out.

Best regards,
